% files = ['radioBasicTest_amp4_800Hz.nlg',...
%          'radioBasicTest_amp4_1000Hz.nlg',...
%          'radioBasicTest_amp4_1200Hz.nlg',...         
%          'radioBasicTest_amp4_1500Hz.nlg',...
%          'radioBasicTest_amp4_3200Hz.nlg',...
%          'radioBasicTest_amp4_4200Hz.nlg',...
%          'radioBasicTest_amp4_5000Hz.nlg',...         
%          'radioBasicTest_amp4_6400Hz.nlg'];
% Fs = 31250;
     
files = {'radioBasicTFSDIV=7_amp4_800Hz.nlg',...
         'radioBasicTFSDIV=7_amp4_1000Hz.nlg',...
         'radioBasicTFSDIV=7_amp4_1200Hz.nlg',...
         'radioBasicTFSDIV=7_amp4_1500Hz.nlg',...
         'radioBasicTFSDIV=7_amp4_2000Hz.nlg',...
         'radioBasicTFSDIV=7_amp4_2800Hz.nlg',...
         'radioBasicTFSDIV=7_amp4_3200Hz.nlg',...
         'radioBasicTFSDIV=7_amp4_4200Hz.nlg',...
         'radioBasicTFSDIV=7_amp4_5000Hz.nlg',...
         'radioBasicTFSDIV=7_amp4_6400Hz.nlg'};
Fs = 29761.9;
close all;     
for i=1:numel(files),
    channels = plot_raw_channels(files{i});
    spectrum=plot_fft(channels(4,:), Fs);
    substrs = strsplit(files{i}, '_');
    freq = strsplit(substrs{3}, 'Hz');
    freq = freq{1};
    title(sprintf('%dHz spectrum', str2num(freq)));
end