def write_W1():
    filename = 'W1.csv'
    f = open(filename, 'w')
    for group in range(31,-1,-1):
        ch1 = 'CH'+str(group + 64)
        ch2 = 'CH'+str(group + 96)
        ch3 = 'CH'+str(group)
        ch4 = 'CH'+str(group + 32)
        f.write(ch1 + ' IIR: y4(n-2)\t' + ch2 + ' IIR: y4(n-2)\n')
        f.write(ch1 + ' IIR: y4(n-1)\t' + ch2 + ' IIR: y4(n-1)\n')
        f.write(ch1 + ' IIR: y3(n-2)\t' + ch2 +' IIR: y3(n-2)\n')
        f.write(ch1 + ' IIR: y3(n-1)\t' + ch2 +' IIR: y3(n-1)\n')
        f.write(ch1 + ' IIR: y2(n-2)\t' + ch2 +' IIR: y2(n-2)\n')
        f.write(ch1 + ' IIR: y2(n-1)\t' + ch2 +' IIR: y2(n-1)\n')
        f.write(ch1 + ' IIR: y1(n-2)\t' + ch2 +' IIR: y1(n-2)\n')
        f.write(ch1 + ' IIR: y1(n-1)\t' + ch2 +' IIR: y1(n-1)\n')
        f.write(ch1 + ' IIR: x1(n-2)\t' + ch2 +' IIR: x1(n-2)\n')
        f.write(ch1 + ' IIR: x1(n-1)\t' + ch2 +' IIR: x1(n-1)\n')
        f.write(ch1 + ' integrator output\t' + ch2 + ' integrator output\n')
        f.write(ch1 + ' integrator output(sat)\t' + ch2 + ' integrator output(sat)\n')
        f.write(ch1 + ' AGC gain\t' + ch2 + ' AGC gain\n')
        f.write(ch1 + ' integrator mean\t' + ch2 + ' integrator mean\n')

        f.write(ch3 + ' IIR: y4(n-2)\t' + ch4 + ' IIR: y4(n-2)\n')
        f.write(ch3 + ' IIR: y4(n-1)\t' + ch4 + ' IIR: y4(n-1)\n')
        f.write(ch3 + ' IIR: y3(n-2)\t' + ch4 +' IIR: y3(n-2)\n')
        f.write(ch3 + ' IIR: y3(n-1)\t' + ch4 +' IIR: y3(n-1)\n')
        f.write(ch3 + ' IIR: y2(n-2)\t' + ch4 +' IIR: y2(n-2)\n')
        f.write(ch3 + ' IIR: y2(n-1)\t' + ch4 +' IIR: y2(n-1)\n')
        f.write(ch3 + ' IIR: y1(n-2)\t' + ch4 +' IIR: y1(n-2)\n')
        f.write(ch3 + ' IIR: y1(n-1)\t' + ch4 +' IIR: y1(n-1)\n')
        f.write(ch3 + ' IIR: x1(n-2)\t' + ch4 +' IIR: x1(n-2)\n')
        f.write(ch3 + ' IIR: x1(n-1)\t' + ch4 +' IIR: x1(n-1)\n')
        f.write(ch3 + ' integrator output\t' + ch4 + ' integrator output\n')
        f.write(ch3 + ' integrator output(sat)\t' + ch4 + ' integrator output(sat)\n')
        f.write(ch3 + ' AGC gain\t' + ch4 + ' AGC gain\n')
        f.write(ch3 + ' integrator mean\t' + ch4 + ' integrator mean\n')

    f.close()
